USE [master]
GO
/****** 物件:  Database [FruitBarDB]    指令碼日期: 2026/7/12 上午 05:24:21 ******/
CREATE DATABASE [FruitBarDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FruitBarDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\FruitBarDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FruitBarDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\FruitBarDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FruitBarDB] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FruitBarDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FruitBarDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FruitBarDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FruitBarDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FruitBarDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FruitBarDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FruitBarDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FruitBarDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FruitBarDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FruitBarDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FruitBarDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FruitBarDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FruitBarDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FruitBarDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FruitBarDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FruitBarDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FruitBarDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FruitBarDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FruitBarDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FruitBarDB] SET  MULTI_USER 
GO
ALTER DATABASE [FruitBarDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FruitBarDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FruitBarDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FruitBarDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FruitBarDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FruitBarDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [FruitBarDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FruitBarDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [FruitBarDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FruitBarDB]
GO
/****** 物件:  Schema [Fruitbar]    指令碼日期: 2026/7/12 上午 05:24:22 ******/
CREATE SCHEMA [Fruitbar]
GO
/****** 物件:  Table [Fruitbar].[AlbumArtist]    指令碼日期: 2026/7/12 上午 05:24:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[AlbumArtist](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AlbumId] [int] NOT NULL,
	[ArtistId] [int] NOT NULL,
	[CreditRoles] [nvarchar](200) NULL,
 CONSTRAINT [PK_AlbumArtist] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_AlbumArtist_AlbumId_ArtistId] UNIQUE NONCLUSTERED 
(
	[AlbumId] ASC,
	[ArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[Albums]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[Albums](
	[AlbumId] [int] IDENTITY(1,1) NOT NULL,
	[AlbumName] [nvarchar](200) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[ReleaseDate] [date] NULL,
	[CoverPic] [varbinary](max) NULL,
	[AlbumType] [nvarchar](50) NULL,
 CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED 
(
	[AlbumId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[Artists]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[Artists](
	[ArtistId] [int] IDENTITY(1,1) NOT NULL,
	[ArtistName] [nvarchar](200) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[ArtistType] [nvarchar](50) NULL,
 CONSTRAINT [PK_Artists] PRIMARY KEY CLUSTERED 
(
	[ArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[ArtistsSongs]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[ArtistsSongs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SongId] [int] NOT NULL,
	[ArtistId] [int] NOT NULL,
	[CreditRoles] [nvarchar](200) NULL,
 CONSTRAINT [PK_ArtistsSongs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ArtistsSongs_SongId_ArtistId] UNIQUE NONCLUSTERED 
(
	[SongId] ASC,
	[ArtistId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[Genre]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[Genre](
	[GenreId] [int] IDENTITY(1,1) NOT NULL,
	[GenreName] [nvarchar](50) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Genre] PRIMARY KEY CLUSTERED 
(
	[GenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Genre_GenreName] UNIQUE NONCLUSTERED 
(
	[GenreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[SongGenres]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[SongGenres](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SongId] [int] NOT NULL,
	[GenreId] [int] NOT NULL,
 CONSTRAINT [PK_SongGenres] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SongGenres_SongId_GenreId] UNIQUE NONCLUSTERED 
(
	[SongId] ASC,
	[GenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[Songs]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[Songs](
	[SongId] [int] IDENTITY(1,1) NOT NULL,
	[SongName] [nvarchar](200) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Lyrics] [nvarchar](max) NULL,
	[Duration] [int] NULL,
 CONSTRAINT [PK_Songs] PRIMARY KEY CLUSTERED 
(
	[SongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** 物件:  Table [Fruitbar].[SongsAlbums]    指令碼日期: 2026/7/12 上午 05:24:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Fruitbar].[SongsAlbums](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AlbumId] [int] NOT NULL,
	[SongId] [int] NOT NULL,
	[TrackNumber] [int] NOT NULL,
 CONSTRAINT [PK_SongsAlbums] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SongsAlbums_AlbumId_SongId] UNIQUE NONCLUSTERED 
(
	[AlbumId] ASC,
	[SongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SongsAlbums_AlbumId_TrackNumber] UNIQUE NONCLUSTERED 
(
	[AlbumId] ASC,
	[TrackNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Fruitbar].[Albums] ADD  CONSTRAINT [DF_Albums_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [Fruitbar].[Albums] ADD  CONSTRAINT [DF_Albums_AlbumType]  DEFAULT (N'Album') FOR [AlbumType]
GO
ALTER TABLE [Fruitbar].[Artists] ADD  CONSTRAINT [DF_Artists_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [Fruitbar].[Genre] ADD  CONSTRAINT [DF_Genre_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [Fruitbar].[Songs] ADD  CONSTRAINT [DF_Songs_IsDeleted]  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [Fruitbar].[AlbumArtist]  WITH CHECK ADD  CONSTRAINT [FK_AlbumArtist_Albums] FOREIGN KEY([AlbumId])
REFERENCES [Fruitbar].[Albums] ([AlbumId])
GO
ALTER TABLE [Fruitbar].[AlbumArtist] CHECK CONSTRAINT [FK_AlbumArtist_Albums]
GO
ALTER TABLE [Fruitbar].[AlbumArtist]  WITH CHECK ADD  CONSTRAINT [FK_AlbumArtist_Artists] FOREIGN KEY([ArtistId])
REFERENCES [Fruitbar].[Artists] ([ArtistId])
GO
ALTER TABLE [Fruitbar].[AlbumArtist] CHECK CONSTRAINT [FK_AlbumArtist_Artists]
GO
ALTER TABLE [Fruitbar].[ArtistsSongs]  WITH CHECK ADD  CONSTRAINT [FK_ArtistsSongs_Artists] FOREIGN KEY([ArtistId])
REFERENCES [Fruitbar].[Artists] ([ArtistId])
GO
ALTER TABLE [Fruitbar].[ArtistsSongs] CHECK CONSTRAINT [FK_ArtistsSongs_Artists]
GO
ALTER TABLE [Fruitbar].[ArtistsSongs]  WITH CHECK ADD  CONSTRAINT [FK_ArtistsSongs_Songs] FOREIGN KEY([SongId])
REFERENCES [Fruitbar].[Songs] ([SongId])
GO
ALTER TABLE [Fruitbar].[ArtistsSongs] CHECK CONSTRAINT [FK_ArtistsSongs_Songs]
GO
ALTER TABLE [Fruitbar].[SongGenres]  WITH CHECK ADD  CONSTRAINT [FK_SongGenres_Genre] FOREIGN KEY([GenreId])
REFERENCES [Fruitbar].[Genre] ([GenreId])
GO
ALTER TABLE [Fruitbar].[SongGenres] CHECK CONSTRAINT [FK_SongGenres_Genre]
GO
ALTER TABLE [Fruitbar].[SongGenres]  WITH CHECK ADD  CONSTRAINT [FK_SongGenres_Songs] FOREIGN KEY([SongId])
REFERENCES [Fruitbar].[Songs] ([SongId])
GO
ALTER TABLE [Fruitbar].[SongGenres] CHECK CONSTRAINT [FK_SongGenres_Songs]
GO
ALTER TABLE [Fruitbar].[SongsAlbums]  WITH CHECK ADD  CONSTRAINT [FK_SongsAlbums_Albums] FOREIGN KEY([AlbumId])
REFERENCES [Fruitbar].[Albums] ([AlbumId])
GO
ALTER TABLE [Fruitbar].[SongsAlbums] CHECK CONSTRAINT [FK_SongsAlbums_Albums]
GO
ALTER TABLE [Fruitbar].[SongsAlbums]  WITH CHECK ADD  CONSTRAINT [FK_SongsAlbums_Songs] FOREIGN KEY([SongId])
REFERENCES [Fruitbar].[Songs] ([SongId])
GO
ALTER TABLE [Fruitbar].[SongsAlbums] CHECK CONSTRAINT [FK_SongsAlbums_Songs]
GO
ALTER TABLE [Fruitbar].[SongsAlbums]  WITH CHECK ADD  CONSTRAINT [CK_SongsAlbums_TrackNumber] CHECK  (([TrackNumber]>(0)))
GO
ALTER TABLE [Fruitbar].[SongsAlbums] CHECK CONSTRAINT [CK_SongsAlbums_TrackNumber]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Unit: second' , @level0type=N'SCHEMA',@level0name=N'Fruitbar', @level1type=N'TABLE',@level1name=N'Songs', @level2type=N'COLUMN',@level2name=N'Duration'
GO
USE [master]
GO
ALTER DATABASE [FruitBarDB] SET  READ_WRITE 
GO
