//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFruitBar8000.DataEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumArtists = new HashSet<AlbumArtist>();
            this.SongsAlbums = new HashSet<SongsAlbum>();
        }
    
        public int AlbumId { get; set; }
        public string AlbumName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public byte[] CoverPic { get; set; }
        public string AlbumType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumArtist> AlbumArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsAlbum> SongsAlbums { get; set; }
    }
}
