//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFruitBar8000.DataEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistsSong
    {
        public int Id { get; set; }
        public int SongId { get; set; }
        public int ArtistId { get; set; }
        public string CreditRoles { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Song Song { get; set; }
    }
}
